### PR TITLE
changed emoji 🇺🇸

### LINKED ISSUE #115: change the NA globe to an american flag emoji when in NA-view of a JP buffed card
https://github.com/TsubakiBotPad/tsutils/blob/master/tsutils/tsubaki/monster_header.py#L18

### PR DESCRIPTION
**Pull request by aliceyzhou**
🌎 -> 🇺🇸

closes #115

### CODE REVIEW

**Comment by chasehult** [comment]
I think it's only supposed to be a flag if the card is JP Buffed

**Comment by aliceyzhou** [comment]
is it supposed to still display the globe for NA view of non-buffed card?

**Comment by RheingoldRiver** [comment]
you know what, I lied in my ticket, this was only supposed to replace the emoji name, not add additional logic. I'm sorry about that

**Comment by aliceyzhou** [comment]
should I revert it back to the first commit then?

**Comment by RheingoldRiver** [comment]
yeah, first commit was right

**Pull request merged**
